displayName: Provider Plugin Demo
type: provider

import: github.com/zalbiraw/traefik-provider

summary: 'Traefik provider that will allow you to discover other Traefik instances configuration. The plugin will allow you to filter and overide discovered config as well as group discvered services and introduces tunneling concept for services.'

testData:
  pollInterval: "5s"
  providers:
  - name: "cluster-1"
    connection:
      # host: ["localhost"]
      # port: 8080
      # path: "/api/rawdata"
      # timeout: "15s"
      # headers: {}
      mTLS:
        caFile: /path/to/ca.crt
        certFile: /path/to/cert.crt
        keyFile: /path/to/key
    tunnels:
      # - name: tunnel1
      #   addresses: [
      #     "http://localhost:8080",
      #   ]
        mTLS:
          caFile: /path/to/ca.crt
          certFile: /path/to/cert.crt
          keyFile: /path/to/key
    http:
      discover: true
      routers:
        discover: true
        discoverPriority: false
        filters:
          name: "^(?!.*@internal$).*"
          entrypoints: []
          rule: ""
          service: ""
        overrides:
          rules:
          # Set
          - value: "Host(`app.traefik.cloud`)"
            filters: 
              rule: "Host(`app.traefik.localhost`)"
          # Regex
          - value: "$1 && PathPrefix(`/api/`)"
            filters: 
              rule: "Host(`app.traefik`) && PathPrefix(`/api/`)"
          entrypoints:
          # Set
          - value: ["websecure"]
            filters: 
              entrypoints: ["web"]
          # Append
          - value: "websecure"
            filters: 
              entrypoints: ["web"]
          services:
          # Set
          - value: "apps"
            filters: 
              service: "app[123]"
          # Regex
          - value: "$1-service"
            filters: 
              service: "app[123]"
          middlewares:
          # Set
          - value: ["jwt", "ratelimit"]
            filters: 
              entrypoints: ["web"]
          # Append, if prepend is required, it can bed done at entrypoint level, this allows the notation to be simple
          - value: "ratelimit"
            filters: 
              name: "app[123]"
        extraRoutes: []
      middlewares: 
        discover: true
        filters:
          name: ""
        extraMiddlewares: []
      services:
        discover: true
        filters:
          name: ""
        overrides:
          servers:
          - strategy: ""
            value: []
            filters: {}
          - strategy: ""
            value: ""
            filters: {}
          - tunnel: "tunnel1"
            filters: {}
          healthchecks:
          - path: ""
            interval: "15s"
            timeout: "10s"
            filters: {}
        extraServices: []
      serverTransports:
        discover: true
        filters:
          name: ""
        extraServerTransports: []
    tcp:
      discover: true
      routers:
        discover: true
        filters:
          name: ""
          entrypoints: []
          rule: ""
          service: ""
        overrides:
          rules:
          # Set
          - value: "HostSNI(`app.traefik.cloud`)"
            filters: 
              rule: "HostSNI(`app.traefik.localhost`)"
          # Regex
          - value: "$1 && HostSNI(`dev.app.traefik`)"
            filters: 
              rule: "HostSNI(`app.traefik`)"
          entrypoints:
          # Set
          - value: ["websecure"]
            filters: 
              entrypoints: ["web"]
          # Append
          - value: "websecure"
            filters: 
              entrypoints: ["web"]
          services:
          # Set
          - value: "apps"
            filters: 
              service: "app[123]"
          # Regex
          - value: "$1-service"
            filters: 
              service: "app[123]"
          middlewares:
          # Set
          - value: ["ip-allow-list"]
            filters: 
              entrypoints: ["web"]
          # Append
          - value: "internal-network-allow-list"
            filters: 
              name: "app[123]"
        extraRoutes: []
      middlewares:
        discover: true
        filters:
          name: ""
        extraMiddlewares: []
      services:
        discover: true
        filters:
          name: ""
        overrides:
          servers:
          - strategy: ""
            value: []
            filters: {}
          - strategy: ""
            value: ""
            filters: {}
          - tunnel: "tunnel1"
            filters: {}
        extraServices: []
    udp:
      discover: true
      routers:
        discover: true
        filters:
          name: ""
          entrypoints: []
          service: ""
        overrides:
          services:
          # Set
          - value: "apps"
            filters: 
              service: "app[123]"
          # Regex
          - value: "$1-service"
            filters: 
              service: "app[123]"
        extraRoutes: []
      services:
        discover: true
        filters:
          name: ""
        overrides:
          servers:
          - strategy: ""
            value: []
            filters: {}
          - strategy: ""
            value: ""
            filters: {}
          - tunnel: "tunnel1"
            filters: {}
        extraServices: []
    tls:
      discover: true
