services:
  traefik-main:
    image: traefik:v3.5
    container_name: traefik-main
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.tcp-ep.address=:8000"
      - "--entrypoints.udp-ep.address=:9000/udp"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8000:8000"
      - "9000:9000/udp"
    volumes:
      - ./configs/traefik-main/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

  traefik-provider1:
    image: traefik:v3.5
    container_name: traefik-provider1
    command:
      - "--api.insecure=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.tcp-ep.address=:8000"
      - "--entrypoints.udp-ep.address=:9000/udp"
    ports:
      - "8081:8080"
      - "8001:80"
      - "8443:443"
      - "8010:8000"
      - "9001:9000/udp"
    volumes:
      - ./configs/traefik-provider1:/etc/traefik/dynamic:ro
      - ./configs/traefik-provider1/ssl:/etc/ssl:ro
    networks:
      - traefik

  traefik-provider2:
    image: traefik:v3.5
    container_name: traefik-provider2
    command:
      - "--api.insecure=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.tcp-ep.address=:8000"
      - "--entrypoints.udp-ep.address=:9000/udp"
    ports:
      - "8082:8080"
      - "8002:80"
      - "8444:443"
      - "8020:8000"
      - "9002:9000/udp"
    volumes:
      - ./configs/traefik-provider2:/etc/traefik/dynamic:ro
      - ./configs/traefik-provider2/ssl:/etc/ssl:ro
    networks:
      - traefik

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - traefik

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    networks:
      - traefik

  tcp-echo:
    image: hashicorp/http-echo
    container_name: tcp-echo
    command: ["-text=TCP Echo Service", "-listen=:8080"]
    networks:
      - traefik

  udp-echo:
    image: alpine
    container_name: udp-echo
    command: ["sh", "-c", "apk add --no-cache netcat-openbsd && while true; do echo 'UDP Echo Response' | nc -u -l -p 8080; done"]
    networks:
      - traefik

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - traefik

networks:
  traefik:
    driver: bridge
